### ISSUE TITLE
Use Cap'n Proto types as data types

### ISSUE THREAD

**Issue by DemiMarie** [zenhack/haskell-capnp#1]
Data structures generated by Cap'n Proto should consist of pointers to memory owned by the deserializer.  This is to allow for zero decoding.

In GHC, dereferencing a pointer is as fast as in C, so this should introduce no overhead.  Phantom type parameters can be used to prevent the pointers from outliving the memory they point to.

**Comment by zenhack** [comment]
Quoting Demi Marie Obenour (2017-06-15 20:03:34)

>    Data structures generated by Cap'n Proto should consist of pointers to
>    memory owned by the deserializer. This is to allow for zero decoding.
>
>    In GHC, dereferencing a pointer is as fast as in C, so this should
>    introduce no overhead. Phantom type parameters can be used to prevent
>    the pointers from outliving the memory they point to.

We need to keep a reference to the message anyway in order to deal with
things like bounds checking, and resolving far pointers. So once you're
doing that anyway I don't think we end up butting heads with the GC?

I guess we could store the reference in some monadic state, since
everything's already monadic in order to deal with the traversal limit.
And then, yeah, we could make use of the same trick the ST monad uses to
make sure those pointers are unusable once we leave the monad. Is that
what you were referring to?

We probably ought to support the message being a Foreign.Ptr for use
with mmapping at least. And ByteArray is probably a better fit than
Vector.

**Comment by zenhack** [comment]
So, having chewed on it a bit I actually actively dislike using the rank-2 ST monad trick as I described above for readers; It seems like an unnecessary restriction, and would make the library harder to use with no clear benefit. (It would make the various types in Data.CapNProto.Untyped a bit smaller, but I'm not going to buy that argument without some benchmarks). Writing is a different story, but that's going to have to be in some instance of PrimMonad to work with zero-copy anyway.

We really *should* deal with the fact that we're endianness dependent right now -- this is at least *correct* for the moment, since we're actually doing the conversion where necessary when reading the data structure in, but this precludes mmap. I'm going to open a separate issue for that.

I don't think there's anything else in this issue that hasn't been addressed, so I'm going to close. If I've misunderstood what you were getting at or missed something, please feel free to re-open.
