### ISSUE TITLE
cannot build with latest ghc on osx

### ISSUE THREAD

**Issue by theobat** [zenhack/haskell-capnp#25]
Hi, I'd like to participate in the implementation of haskell-capnp but did not manage to build the project.. I might be doing something wrong I'm quite new to haskell

Cannot build with:
```
➜  haskell-capnp git:(master) ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.2.2
➜  haskell-capnp git:(master) cabal --version
cabal-install version 2.0.0.1
compiled using version 2.0.1.1 of the Cabal library 
```

I get the following:
```
➜  haskell-capnp git:(master) make build    
cabal configure --enable-tests
Resolving dependencies...
Warning: solver failed to find a solution:
Could not resolve dependencies:
rejecting: capnp-0.1.0.0:!test (constraint from config file, command line
flag, or user target requires opposite flag selection)
trying: capnp-0.1.0.0:*test
unknown package: reinterpret-cast (dependency of capnp-0.1.0.0:*test)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: capnp-0.1.0.0:test, capnp,
reinterpret-cast
Trying configure anyway.
Configuring capnp-0.1.0.0...
cabal: Encountered missing dependencies:
bytes -any,
cereal -any,
dlist -any,
exceptions -any,
heredoc -any,
quota -any,
reinterpret-cast -any,
resourcet -any,
test-framework -any,
test-framework-hunit -any,
test-framework-quickcheck2 -any,
utf8-string -any
make: *** [configure] Error 1
```

The nix way of building fails either with:
```
➜  haskell-capnp git:(master) nix --version
nix (Nix) 2.0
```
```
➜  haskell-capnp git:(master) make nix-build
nix-build --no-out-link release.nix -A capnp -j 8
building '/nix/store/hb7vix7qb2q8qwjjynayw9p26h5kna8s-nixpkgs-788ce6e3df12bb0cf19fb9ccf8ffa75558b551ba-src.drv'...
dyld: Library not loaded: /usr/lib/system/libsystem_coretls.dylib
  Referenced from: /nix/store/v7i520r9c2p8z6vk26n53hfrxgqn8cl9-Libsystem-osx-10.11.6/lib/libSystem.B.dylib
  Reason: image not found
builder for '/nix/store/hb7vix7qb2q8qwjjynayw9p26h5kna8s-nixpkgs-788ce6e3df12bb0cf19fb9ccf8ffa75558b551ba-src.drv' failed due to signal 6 (Abort trap: 6)
error: build of '/nix/store/hb7vix7qb2q8qwjjynayw9p26h5kna8s-nixpkgs-788ce6e3df12bb0cf19fb9ccf8ffa75558b551ba-src.drv' failed
make: *** [nix-build] Error 1
```

**Comment by zenhack** [comment]
It's entirely possible the nix build is broken for MacOS; I don't know that anyone's tried it before.

Regarding the normal cabal invocation, you need to install the dependencies first. `cabal install --only-dependencies`. Note that you'll also need https://github.com/zenhack/haskell-quota, which is still not on hackage.

I mostly use `new-build`, which will pull in the dependencies automatically. If you check out the above repository next to `haskell-capnp`, and place this in a file `cabal.project.local` at the root of the `haskell-capnp` repo:

```
packages:
  *.cabal
  ../haskell-quota/*.cabal
tests:
  True
```

Then `cabal new-build` should do the trick.

The nix stuff is mainly of use to me because it the travis nix support is better than the Haskell support, but it was contributed by someone else and I've never been able to be bothered to do more than keep it limping along.

Also, just as a general heads up, I don't really want to promise much involvement in the project myself; I kinda lost interest a while back, and while I could see getting back into it (especially with some other folks contributing), I wouldn't want someone to invest a bunch of time expecting a project that's actively maintained and developed, only to find that it it isn't.

**Comment by theobat** [comment]
All right thank you for the clarification. I'm not sure I'll invest much time in the project then - for now.
The haskell-quota repo and the cabal.project.local file did the trick, I managed to build the project.

Just out of curiosity, did you lose interest in haskell entirely or is it just the capnp side, or something entirely different ?

**Comment by zenhack** [comment]
Quoting theobat (2018-03-14 10:15:04)

>    The haskell-quota repo and the cabal.project.local file did the trick,
>    I managed to build the project.

Glad to hear it.

>    Just out of curiosity, did you lose interest in haskell entirely or is
>    it just the capnp side, or something entirely different ?

Just the capnp side.

**Comment by zenhack** [comment]
@theobat, in case you're still interested, I've found myself digging into this again -- I will probably be more responsive than previously suggested.

Also, the quota dependency/cabal.project.local is no longer necessary; I decided to fold the relevant functionality into haskell-capnp proper.

**Comment by zenhack** [comment]
Closing this, since the actual issue is resolved.
