### ISSUE TITLE
Document work to be done

### ISSUE THREAD

**Issue by taktoa** [zenhack/haskell-capnp#5]
Hi, I'm strongly interested in contributing to this project (in fact, I am contemplating working on this as part of one of my CS classes this semester), but it is unclear to me what needs to be done.

I have pretty extensive experience in writing Haskell (e.g.: I wrote [language-ninja](https://github.com/awakesecurity/language-ninja)), and I've been increasingly looking into Cap'n Proto. I am particularly interested in Cap'n RPC; I think it may be interesting to incorporate information about Cap'n RPC protocols at the type level (using session types or something similar) in the generated output.

Also, if there were an IRC channel or similar synchronous way to get in touch with you regarding this project, I believe it would greatly improve efficiency of communication, especially since it seems like you are actively working on this project every day.

**Comment by zenhack** [comment]
Quoting Remy Goldschmidt (2017-09-04 08:29:54)

>    Hi, I'm strongly interested in contributing to this project (in fact, I
>    am contemplating working on this as part of one of my CS classes this
>    semester), but it is unclear to me what needs to be done.

Cool! I will totally prioritize roadmap-style docs then.

>    Also, if there were an IRC channel or similar synchronous way to get in
>    touch with you regarding this project, I believe it would greatly
>    improve efficiency of communication, especially since it seems like you
>    are actively working on this project every day.

I often hang out in #sandstorm on Freenode, which is probably the most
topical channel for capnproto stuff in general.

**Comment by zenhack** [comment]
(My nick on freenode is isd, FTR)

**Comment by zenhack** [comment]
So, a quick brain dump: right now I'm working on being able to read the data structures defined in schema.capnp:

https://github.com/capnproto/capnproto/blob/master/c%2B%2B/src/capnp/schema.capnp

Which are output by the schema compiler -- the file `testdata/schema-codegenreq` in this repository is the output of the schema compiler on `schema.capnp`, so it's root is a `CodeGeneratorRequest`. Files of immediate interest:

* Everything under `Schema/CapNProto/Reader`
* `Data/CapNProto/TH.hs`
* `Tests/WalkSchemaCodeGenRequest.hs`

There's a lot of grunt work here, since we're basically doing the work of the schema compiler plugin manually (because it doesn't exist yet).

The source tree could use some re-arranging; as of late I've been a bit lazy and have just shoved some things in `Data/` that probably belong elsewhere (e.g. now that we're actually messing with the schema it may make sense to have a `Language/` subdir).

**Comment by zenhack** [comment]
@taktoa, I just dumped a handful of issues on the tracker; some of these can probably be worked on independently to what I'm doing right now. Let me know if anything seems interesting.

**Comment by taktoa** [comment]
Great! I'll check that out later today.

**Comment by zenhack** [comment]
I'm going to close this; there's not an obvious actionable thing to do for this issue right now. Will try to keep TODOs on the issue tracker.
