### ISSUE TITLE
Suggestion: use `monad-ste`

### ISSUE THREAD

**Issue by mitchellwrosen** [zenhack/haskell-capnp#66]
As discussed in person ;)

**Comment by zenhack** [comment]
I'm going to close this without doing anything. Reasoning:

- `LimitT (STE SomeException s)` already satisfies the type class constraints, so users of the library can use monad-ste if they want.
- While monomorphizing might improve performance, it boxes us into some constraints I'm not satisfied with. E.g. if we want to mutate messages in IO (possibly allowing us to manipulate memory-mapped files in-place) we won't be able to do that with STE; there's a function `stToIO` that it doesn't appear exists in `monad-ste`
- The library hasn't been updated since 2016, and I'm dubious of adding a dependency on it.

I could see a similar abstraction to STE replacing the `RWCtx` constraint we have now, but I don't think this is quite the right solution as-is.

Sorry it took me years to respond to this :/
